### ISSUE TITLE
Cannot get high confidence region (HCR) in the gui

### ISSUE THREAD

**Issue by kts707** [rahul-goel/isrf_code#1]
Hi Rahul,

Thanks for the great work!

I followed the commands in the README to train a `horns` scene and opened this scene in the provided GUI. However, after I create the strokes and click `get hcr`, it does not display the selected area and nothing happens. At the same time I am getting some error messages from the terminal as shown below. Do you know what the problem is and how to fix this issue? Thanks a lot!

```
Buliding K Means Model.
Traceback (most recent call last):
  File "/home/user/isrf_code/gui.py", line 222, in hcr_callback
    STATE["faiss_kmeans"] = run.do_kmeans_clustering_multiview(STATE["stroke_index"], STATE["features"])
  File "/home/user/anaconda3/envs/isrf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/isrf_code/run.py", line 1091, in do_kmeans_clustering_multiview
    faiss_kmeans = kmeans(all_features)
  File "/home/user/anaconda3/envs/isrf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/isrf_code/segment_3d.py", line 48, in kmeans
    kmeans.train(fv.contiguous())
  File "/home/user/anaconda3/envs/isrf/lib/python3.9/site-packages/faiss/__init__.py", line 1560, in train
    clus.train(x, self.index, weights)
  File "/home/user/anaconda3/envs/isrf/lib/python3.9/site-packages/faiss/__init__.py", line 68, in replacement_train
    self.train_c(n, swig_ptr(x), index)
  File "/home/user/anaconda3/envs/isrf/lib/python3.9/site-packages/faiss/swigfaiss_avx2.py", line 10348, in swig_ptr
    return _swigfaiss_avx2.swig_ptr(a)
ValueError: input not a numpy array
```

The screenshot of the GUI is shown below as well:

![isrf_gui](https://user-images.githubusercontent.com/59402345/228749745-6a973147-b51e-4017-9292-0f11d8dc18fe.PNG)

**Comment by rahul-goel** [comment]
Hi!

I think this is an issue with the library `faiss`. Some versions of it allow us to directly pass torch tensors while for some we have to convert them to numpy first.

You can try changing [this line](https://github.com/rahul-goel/isrf_code/blob/main/segment_3d.py#L47) to `kmeans.train(fv.contiguous().numpy())` and similarly [this line](https://github.com/rahul-goel/isrf_code/blob/main/segment_3d.py#L57) to `dist, _ = kmeans.index.search(fg.numpy(), 1)`.

It may be a bit slower.
