### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by Sugar0725** [rahul-goel/isrf_code#8]
Hello, Thank you for your excellent work, but I encountered a problem on my windows machine. Can this project support running on a windows machine? If so, how can I solve this problem?
```
Using C:\Users\Sugarkiller\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116 as PyTorch extensions root...
Traceback (most recent call last):
  File "D:\Pycharm\Pycharm_Project\isrf_code-main\run.py", line 14, in <module>
    from lib import utils, dvgo, dcvgo, dmpigo
  File "D:\Pycharm\Pycharm_Project\isrf_code-main\lib\utils.py", line 11, in <module>
    from .masked_adam import MaskedAdam
  File "D:\Pycharm\Pycharm_Project\isrf_code-main\lib\masked_adam.py", line 7, in <module>
    adam_upd_cuda = load(
  File "F:\Anaconda3\envs\isrf\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "F:\Anaconda3\envs\isrf\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "F:\Anaconda3\envs\isrf\lib\site-packages\torch\utils\cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "F:\Anaconda3\envs\isrf\lib\site-packages\torch\utils\cpp_extension.py", line 1648, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
```

**Comment by rahul-goel** [comment]
Hi.

Perhaps try `pip install ninja` in the python environment to install Ninja which seems to be missing. The project has **not** been tested with Windows so whether it will work or not is uncertain.

Regards,
Rahul Goel

**Comment by Sugar0725** [comment]
Thanks for your generous answer, but I found new problems when I installed ninja：
```
FAILED: adam_upd_kernel.cuda.o
RuntimeError: Error building extension 'adam_upd_cuda'
```
It seems to be a compilation problem that I can't solve, so I can only consider using a linux server.

**Comment by rahul-goel** [comment]
Hi.

If you share the entire error, perhaps I can help. The extensions provided by the [DVGO folks ](https://github.com/sunset1995/DirectVoxGO) are not compiliing. The exact error may help to resolve it as well.

Regards,
Rahul Goel

**Comment by Sugar0725** [comment]
Hi.Thank you very much for your quick answer，I will try it later. I still have a question: Can I ask what the configuration of your experimental machine is?My current Windows machine is RTX4060. Is 8G of graphics memory enough?Thank you again for your generous answer

**Comment by rahul-goel** [comment]
Hi.

I don't think 8GB is enough. We tested the code on a linux machine with an RTX 3090 (24 GB).

Regards,
Rahul Goel

**Comment by rahul-goel** [comment]
Closing due to no activity.
